name: build-static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build --output type=local,dest=. --target local .

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(./podman --version | cut -d' ' -f3)"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: "Podman ${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: true

      - name: Upload amd64 asset
        id: upload-amd64-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./podman
          asset_name: podman
          asset_content_type: application/octet-stream
