name: all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:

      - name: Test
        run: |
          bash all.sh
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all
          path: |
            bin
